### ISSUE TITLE
Package version information or yml file for conda environment not availble

### ISSUE THREAD

**Issue by m-d-grunnill** [nextstrain/enterovirus_d68#1]
I couldn't find information on package version in the readme or a yml file in a prominent place.

I am a researcher at Public Health Ontario conducting phylogenetic/dynamic analyses of Enterovirus D68. Unfortunately with some of the latest versions of augur and TimeTree the augur refine function runs into an issue constructing an output json file (see https://github.com/nextstrain/augur/issues/1209) . I found your work on Enterovrius D68 and was hoping from it I could find the correct combination of package versions so I could perform my work Enterovrius D68. Any information on package version combinations you used would be gratefully received.

**Comment by emmahodcroft** [comment]
Hi @m-d-grunnill - I'm so sorry you're having trouble with this. I'm afraid the EV-D68 workflow has been somewhat 'on hold' since the pandemic due to being fully committed to SC2 work (I hope to change this by the end of the year). While I've been running the workflow recently on a recent analysis, it's been on older versions of Nextstrain/Treetime.

I'm currently running Treetime 0.8.6 and augur 14.0.0 (pretty old) as I've not had time to update everything and ensure it still works (seems it wouldn't from your experience!). 
Though not an ideal solution you could try installing these versions (perhaps in particular Treetime) and seeing if this solves your issue?

**Comment by m-d-grunnill** [comment]
Dear @emmahodcroft 
Thanks for this.
Cloning my environment and downgrading augur to 14.0.0 and treetime to 0.8.6 within the cloned environment works. Hopefully when the bug fix (https://github.com/nextstrain/augur/pull/1213) will pass review soon and be included with the next augur release.

**Comment by emmahodcroft** [comment]
Hi @m-d-grunnill - I'm very glad to hear this worked! Hopefully the bug fix will go through soon, but until then I am glad you can at least get things working! (And that it's not something much harder to solve!)
Best,
Emma

**Comment by victorlin** [comment]
@m-d-grunnill the fix has been released in [Augur 22.0.3](https://github.com/nextstrain/augur/releases/tag/22.0.3). You should now be able to use the latest versions of Augur and TreeTime for your analyses. Thank you for your patience!
